version: '3.7'

services:

  sample:
    container_name: fz-react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
